# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

envd = HYPR_CURSOR_THEME,Bibata-Modern-Classic
envd = HYPRCURSOR_SIZE,24
envd = XCURSOR_THEME,Bibata-Modern-Classic
envd = XCURSOR_SIZE,24
envd = QT_CURSOR_THEME,Bibata-Modern-Classic
envd = QT_CURSOR_SIZE,24

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

envd = GTK_THEME,Catppuccin-Red-Dark

# TODO: add to fish env && extract colors
env = SLURP_ARGS, -d -b 00000066 -B 00000066 -c 8B0000A6
